= Untitled Game Engine
Lillian Lynn Mahoney <lillian.lynn.mahoney@gmail.com>
3, 2014-12-29

Game engine for a future planned game, which will be a procedurally-generated item-centric top-down 2D tile-based puzzle/action game vein of __Zelda: Oracle of Ages__ and __Zelda: Oracle of Seasons__ as well as __Zelda: Link's Awakening__.

  * Tile based map rendering and management
  * Game entity management
  * Input handling
  * Resource management
  * For more details please read the wiki's https://github.com/lillian-mahoney/untitled-game-engine/wiki/Current-Features[current features page].

*Future plans:*

  * Procedural generation of various objects
  * Game editor; some rudimentary game editing tools. The editor I have in mind is inspired by http://rpg.hamsterrepublic.com/ohrrpgce/Main_Page[Official Hamster Republic Role Playing Game Construction Engine (OHRRPGCE)].

== Setup

There's only a demo for now; run test.py.

*Dependencies:*

  * http://pygame.org/news.html[pygame]
  * http://www.pythonware.com/products/pil/[pil]

== License: Attribution Assurance License

This will probably change to one of the MIT licenses...

See __license.txt.asc__ which is singed by gnu-pg in FreeBSD. See __license.txt__ for unsigned license.

Clearsigned in FreeBSD, as so:

----
# pkg install gnupg pinentry
$ gpg --gen-key
$ gpg --clearsign license.txt
----
