= Cross-platform 2D tile-based game engine

This repository is in very early development.

Hypatia Engine is a cross-platform game engine for 2D tile-based games, namely inspired by __Zelda: Oracle of Ages__ and __Zelda: Oracle of Seasons__.

Right now the only working demo is +examples/exploremap.py+; you need to run it from +examples/+.

== Key features

  * Compatible with BSD, Linux, Windows, Mac; Python 2.7.6 and Python 3.4.0. Please checkout https://github.com/lillian-lemmer/hypatia-engine/wiki/support[the official wiki page on support].
  * MIT License
  * OpenGL
  * Tile map management
  * Walkabout animations, with support for child Walkabout sprites
  * Game logic automation

== Help/Support

  * https://github.com/lillian-lemmer/hypatia-engine/wiki/Installation-Instructions[Official wiki installation instructions]
  * http://lillian-lemmer.github.io/hypatia-engine/[The official Hypatia Engine website] (donate here!)
  * https://github.com/lillian-lemmer/hypatia-engine/wiki[The official Hypatia Engine wiki] - please read!
  * Official IRC support channel (Freenode): irc.freenode.net #hypatia-engine -- my nick is lillian.

== Examples

You should checkout +examples/exploremap.py+ for a functional demo.

=== tiles module

You use 3D lists of tile names to create a +TileMap+:

```python
import tiles


blueprint = [
             [  # layer
               ['default', 'default', 'default'],  # row
               ['default', 'default', 'default'],
               ['default', 'default', 'default']
             ]
            ]
tilemap = tiles.TileMap('debug', blueprint)
```

You can save a +TileMap+ to file:

```python
tilemap_string = tilemap.to_string()

with open('test.tilemap', 'wb') as f:
    f.write(tilemap_string)
```

You can load a +TileMap+ from file:

```python
tilemap = tiles.tilemap_from_string(tilemap_string)
```

Each tile has its associated +TileProperties+, you can access them via their tile coordinates:

```python
tilemap[(3, 3)]
```

The +TileMap+ object is basically some data + each layer of tiles as a single image in a list:

```python
for surface in tilemap.layer_images:
    # do something with the layer image pygame surface
    pass
```

A +TileSwatch+ defines tile graphics and properties. A tile's properties are set in +tileswatch.ini+. Below the +TileSwatch+ we're defining is +'debug'+, which comes as a default +TileSwatch+ with Hypatia Engine:

```python
tilemap = tiles.TileMap('debug', blueprint)
```

Remember, a +TileSwatch+ is how +TileMap+ knows how to extrapolate +TileProperties+ and graphic data for blitting to the respective layer surface.

