image:media/logo/logo%20(185x46).png["Hypatia"]

image:https://img.shields.io/github/license/mashape/apistatus.svg[MIT License]

Hypatia is a 2D adventure game engine inspired by link:http://en.wikipedia.org/wiki/The_Legend_of_Zelda:_Oracle_of_Seasons_and_Oracle_of_Ages[_Legend of Zelda: Oracle of Ages_ and _Oracle of Seasons_].

There is a functional demo (+example/game.py+) of Hypatia's current capabilities. Here it is in action:

image:https://camo.githubusercontent.com/17fdd3839c7b692a9069c206053edb1809b8d12d/687474703a2f2f692e696d6775722e636f6d2f463465526259532e676966["The demo game in action."]

== About

This repository is in very early development. The development is being guided by the game and technical design documents being made for a game. More info to be announced...

Hypatia is a labor of love, crafted by Lillian Lemmer. Read more link:http://github.com/lillian-lemmer/hypatia/wiki/About-the-Creator[about the creator of Hypatia].

== Support this project

We want to give back to the community to our fullest potential. Unfortunately, some things just cost money; there are things we need to buy and people we need to hire. There are three ways to donate to the Hypatia project (none of which require a sign in):

  * link:https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=YFHB5TMMXMNT6[Donate through PayPal]
  * link:https://www.bountysource.com/teams/hypatia[Donate, or demand features in exchange for cash, through Bountysource] image:https://img.shields.io/bountysource/team/hypatia/activity.svg[Bountysource]
  * link:https://gratipay.com/~lillian-lemmer/[Donate through Gratipay] image:https://img.shields.io/gratipay/lillian-lemmer.svg[Gratipay]

== Documentation, help, and contact

All of the documentation is on the link:http://github.com/lillian-lemmer/hypatia/wiki[GitHub Wiki].

Additional resources:

  * http://lillian-lemmer.github.io/hypatia/[The official Hypatia website]
  * Official IRC support channel: #hypatia on link:http://irc.lillian.link/[irc.lillian.link]
  * You can contact the author via her email: lillian.lynn.lemmer@mgmail.com

== Key features

  * Great support for various platforms:

   ** Operating systems supported: BSD, Linux, Windows, Mac
   ** Python 2 & 3 support
   ** Please checkout https://github.com/lillian-lemmer/hypatia-engine/wiki/support[the official wiki page on support].

  * Permissive MIT License
  * OpenGL
  * Framework spefically for 2D adventure games:

    ** Tile map management
    ** Sprite management
    ** Game logic automation
    ** Dialog management

== License

Hypatia is MIT licensed, which means you don't have to ever worry about legal heat.

----
The MIT License (MIT)

Copyright (c) 2015 Lillian Lemmer

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
----

