#!/bin/sh
#
# **NOTE:** To use this script make sure it is executable and either
# copy it to the '.git/hooks/' directory or create a symbolic link
# named '.git/hooks/pre-push' that points to this script.
#
# A hook to verify what is about to be pushed.  Called by "git push"
# after it has checked the remote status, but before pushing anything.
# If this script exits with a non-zero status nothing will be pushed.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local sha1> <remote ref> <remote sha1>
#
# This script will run the test suite for Hypatia, as defined by
# 'test.sh' in the top-level directory, and will reject the push if
# any tests report errors.
#
# Running git-push with the `--no-verify` flag will cause Git to skip
# this hook, in the event a developer wants to push anyway regardless
# of failing tests.

remote="$1"
url="$2"

test_script="$(git rev-parse --show-toplevel)/test.sh"

exec $test_script
exit $?

