= Game Mechanics Overview
Thomas Almquist <thomas.c.almquist@gmail.com>
0, 2014-10-11

This document is meant to explain all game mechanics found in Untitled Game--henceforth refered to as UG.

== General Overview

UG is a two-dimensional top-down action-adventure game, with gameplay heavily influenced by the 2D Legend of Zelda games and with character stats/item mechanics inspired by the Borderlands franchise. 

Players will be non-linearly exploring a vast world doing things like: killing monsters for loot, buying and selling that loot, and exploring dungeons for super rare loot. 

== Characters

=== Player Character (PC)
Lorem Ipsum

=== Non-Player Characters (NPC)
Lorem Ipsum

=== Monsters/Enemies
Lorem Ipsum

=== Bosses
Lorem Ipsum

== Stats

=== Health Points (HP)
When reduced to zero, character dies.

=== Stamina Points (ST)
Used for attacking, charging, blocking, and boot abilities. 

Recharges automatically.

=== Equipment Proficiencies (EP)
Experience point pools and levels for each kind of weapon (and maybe armor).

=== Defense (DFN)
Item based stat. Modified by EP. Most Common in heavy armor.

Defends against regular damage.

=== Grace (GRC)
Item based stat. Modified by EP. Most common in light armor.

Defends against critical damage.

=== Attack (ATK)
Based on equipped weapon. Modified by EP.

Average amount of damage you deliver when attacking.

=== Speed (SPD)
Based on equipped weapon. Modified by EP.

Number of times per second you can attack.

=== Damage Per Second (DPS)
DPS = ATK * SPD

=== Luck (LUK)
Item based stat. Most common in accessories.

Chance for a rare item drop.

== Level-Up
Need to flesh out EP level-up system.

== Combat
Lorem Ipsum

=== Critical Hits (Crits)
Lorem Ipsum

=== Charging
Lorem Ipsum

=== Blocking
Lorem Ipsum

=== Parry
Lorem Ipsum

=== Dodging
Lorem Ipsum

== Loot System
Lorem Ipsum

=== Random Generation
Lorem Ipsum

=== Drops
Lorem Ipsum

=== Mythic Items
Lorem Ipsum

=== Buying and Selling
Lorem Ipsum

== Equipping Items
Explanation of light/heavy system.

== Weapons
Lorem Ipsum

=== Light Melee
Lorem Ipsum

=== Heavy Melee
Lorem Ipsum

=== Light Projectile
Lorem Ipsum

=== Heavy Projectile
Lorem Ipsum

=== Knives
Lorem Ipsum

=== Grappling Hooks
Lorem Ipsum

== Boots
Lorem Ipsum

=== Sprinting Boots
Lorem Ipsum

=== Jumping Boots
Lorem Ipsum

=== Kicking Boots
Lorem Ipsum

== Armor
Lorem Ipsum

=== Helmuts
Lorem Ipsum

=== Suits
Lorem Ipsum

=== Gauntlets
Lorem Ipsum

=== Accessories
Lorem Ipsum

== World Map and Exploration
Lorem Ipsum

=== Random Events
Lorem Ipsum

=== Terrains
Lorem Ipsum

=== Towns
Lorem Ipsum

=== Dungeons
Lorem Ipsum

== Narrative and Art Style
Lorem Ipsum

